version: "3.7"
services:
  php:
    container_name: cocktail
    image: thecodingmachine/php:8.0-v4-fpm-node14
    ports:
      - "9000:9000"
    tty: true
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_INI_MEMORY_LIMIT=4G
    working_dir: /var/www/html
    networks:
      - cocktail-network

  nginx:
    container_name: cocktail_nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - cocktail-network

  mysql:
    container_name: cocktail_maria
    image: bitnami/mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=cocktail
      - MARIADB_USER=cocktail
      - MARIADB_PASSWORD=cocktail
      - BITNAMI_DEBUG=true
    restart: on-failure
    volumes:
      - cocktail-datavolume:/var/lib/mysql
    networks:
      - cocktail-network

networks:
  cocktail-network:
    driver: bridge

volumes:
  cocktail-datavolume:
